### ISSUE TITLE
Experimental Design

### ISSUE THREAD

**Issue by terryneumann** [ridicholas/fairness_in_fact_checked_info_ecosystem#11]
Typically when one applies the Rubin causal model, they do not have a perfect counterfactual. However, in simulation, you **do** have access to a perfect counterfactual. You can run one iteration with the treatment (t1) and one without (t0) and directly observe the treatment effect.  There are no unobservables. In our case, the treatment effect will be the change in agent ```belief``` associated with launching a check-worthiness algorithm in our different communities.

**Comment by ridicholas** [comment]
yep, no unobservables in our simulation. might be unobservables in real life that we are not taking into account that invalidate our simulation tho
