### ISSUE TITLE
Topic Distribution: Seeding and drawing

### ISSUE THREAD

**Issue by terryneumann** [ridicholas/fairness_in_fact_checked_info_ecosystem#12]
Pseudo code
```
number_draws = random.sample([4,...,20]) 
for draw in range(number_draws):
      draw = sample.softmax(topic_distribution)
      topic_number = random.sample(subtopics[where(topic == draw)])
      information_quality = random.sample([-1, 0, 1], probs = [0.05, 0.8, 0.15])
      agent['inbox'].append([topic_number, information_quality])                       
```

Then, we make individual's topic tweeting behavior dependent on their initial seeding of information (as well as other information in the network)

We can also create a unique softmax for each node in the network by reflecting their topic preference related to their position in the community. If they have high connectivity with the outside-community nodes, $\alpha_{i}$ is small. If they have low connectivity with outside-community nodes, $\alpha_{i}$ is high. So

$\alpha_{i}$ = links in community / total links.

$SharedTopics_{i} = 1$
$CommunityTopics_{i} = 1 + \alpha_{i}$

Then softmax(topics) = $softmax([1, 1+\alpha_{i}$])

**Comment by ridicholas** [comment]
i'm a little unclear on what exactly information is in the og simulation. I think we might need a topic and information object.
