### ISSUE TITLE
step 1: change simulation to use our provided graph. 

### ISSUE THREAD

**Issue by ridicholas** [ridicholas/fairness_in_fact_checked_info_ecosystem#14]
change `create_polarized_network` to read in our network rather than generating new scale free network.

Allow for scale-down. So we read in graph G and scale parameter s. We would randomly remove s% of nodes from the graph that was read in. 

at this step forget about belief towards various topics. Just try and run the code as provided by on our sample network to see if it works as expected. (since polarization is 2 groups towards 1 topic, can just have odd communities be one group and even communities be the other group at this step).

**Comment by terryneumann** [comment]
this will change the community structure a lot, no? the community detection algo might not pick the same community with, say, 70% of nodes removed.

**Comment by ridicholas** [comment]
i am not 100% but i dont think it will. 

here is my reasoning. say you have two communities. the nodes in each community are tightly connected to other nodes in the community, and not tightly connected to nodes outside the community. Remove 70% of nodes randomly from each community, why would the remaining nodes in each community all of a sudden have more connections to nodes outside of the community? the only way it can change the structure significantly is if you dis-proportionally remove 'inner' community nodes (ones that arent connected to the other community) while leaving the ones that are connected to the other community. As long as you do it randomly the ratios and thus community structure should remain.

**Comment by ridicholas** [comment]
we can test this

**Comment by ridicholas** [comment]
added in latest push, closing for now
