### ISSUE TITLE
Add a ```survey``` module to randomly sample check-worthy labels from nodes

### ISSUE THREAD

**Issue by terryneumann** [ridicholas/fairness_in_fact_checked_info_ecosystem#9]
This should be a sample from across the network.

**Comment by terryneumann** [comment]
How do we determine if people vote yes or no? We may consider using some sort of probabilistic assessment dependent on (community, topic, true label).

**Comment by ridicholas** [comment]
im leaving this for later personally. I think I need to focus on solidifying our information generation and propagation understanding/simulation first. Once we have that we can start considering the sampling and fact checking methods that would occur at some time T/2.
